name: website

on: [push, pull_request]

jobs:
  website:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.3

    - name: Set up Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: "3.10"

    - name: Install tox
      run: |
        pip install tox

    - name: Build website
      run: |
        tox -e website

    - name: Deploy (if stable)
      if: github.ref == 'refs/heads/stable'
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: stable
        BRANCH: gh-pages
        FOLDER: website/html/
